// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcWSFGpA9J2jN2hZvc1YCiBi0Mja52OdM',
    appId: '1:529902029138:web:e8413f6f29baa1883c928b',
    messagingSenderId: '529902029138',
    projectId: 'authmail-619ea',
    authDomain: 'authmail-619ea.firebaseapp.com',
    storageBucket: 'authmail-619ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1SI3vZAqfkI-M7I1JkIE5mUvFE5i6mio',
    appId: '1:529902029138:android:fac7b311e5cef8fd3c928b',
    messagingSenderId: '529902029138',
    projectId: 'authmail-619ea',
    storageBucket: 'authmail-619ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Q7bV4P5tIzHDTuVu2d38_nmJJt1-gDA',
    appId: '1:529902029138:ios:600e6f0cc32f6ba13c928b',
    messagingSenderId: '529902029138',
    projectId: 'authmail-619ea',
    storageBucket: 'authmail-619ea.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Q7bV4P5tIzHDTuVu2d38_nmJJt1-gDA',
    appId: '1:529902029138:ios:600e6f0cc32f6ba13c928b',
    messagingSenderId: '529902029138',
    projectId: 'authmail-619ea',
    storageBucket: 'authmail-619ea.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
